name: Publish

on:
  release:
    types: [created]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [10, 12, 14]
    runs-on: ${{matrix.os}}

    steps: actions/checkout@v2
      with:
        node-version: "18.x"
        registry-url: "https://registry.npmjs.org"
    - run: npm ci
    - run npm run build
    - name: Publication to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
